### ISSUE TITLE
Cli and API Wrapper

### ISSUE THREAD

**Issue by joshghent** [esfiddle/code-blocks#2]
I reckon we should turn this repo into the Node module (which we can then publish to NPM) and then create a new repo around this module which encapsulates it as a CLI. What do you think?

This would be useful so we can include this package in our API so we can expose it as an endpoint.

**Comment by preyneyv** [comment]
Yeah that was the plan. I just wanted to hack something together that we can test out. Now that it works, sure, we can make it a module. If you want, I will do that and publish it.

**Comment by joshghent** [comment]
Yeah sounds good, I'll have to see if you will have permissions to publish under the esfiddle namespace to npm. You should do but if not then I will give you access (somehow!)

**Comment by preyneyv** [comment]
Hey Josh, I didn't have permissions to publish under that namespace, so I just published it under my account. It's there as `js-blockify`.

**Comment by joshghent** [comment]
Ok mate, no worries. Thanks a lot. I'll look into this later!

**Comment by joshghent** [comment]
This has been completed!
